### ISSUE TITLE
Should the interior parent nodes be domain separated?

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/bao#19]
Currently we only domain-separate the root node. But I'm worried that leads to collisions (it certainly can if the length overflows) or at the very least makes it harder to prove that the tree mode is sound. I'm adding comments about this in `spec.md`.

**Comment by tarcieri** [comment]
I'd suggest using the RFC 6962 domain separation construction (albeit with BLAKE2 instead of SHA2) which disambiguates leaf nodes from interior nodes using `0x00` and `0x01` respectively.

**Comment by tarcieri** [comment]
RFC 6962 is specifically designed for extensible Merkle log proofs and authenticates roots using digital signatures (i.e. Signed Tree Heads / STHs)

I'm not sure in what case it would actually be necessary to specifically guard against that: distinguishing the interior of the tree from the leaves is necessary to prevent second preimage attacks. That's not the case with the roots though.

You seem to be worried about some sort of length extension attack, but in what care are you not in some way trusting the digest you receive to authenticate the content? If you are authenticating a file using a malicious digest, what stops an attacker from simply handing you a digest of a malicious file?

**Comment by oconnor663** [comment]
Totally, I don't think RFC 6962 has any length extension issues at all. Everything that's being hashed there is public, and my understanding is that length extension only starts being a problem when you're dealing with hash inputs that an attacker isn't supposed to know. I was thinking of a hypothetical situation where someone extracted the Merkle tree mechanism from RFC 6962, and repurposed it for a different application. Kind of pie-in-the-sky.

**Comment by oconnor663** [comment]
Closing this, because we do domain separation now, and the proof framework from "Sufficient conditions for sound tree and sequential hashing modes" also relies on it. I'm actually considering relying entirely on domain separation, and getting rid of the root node length suffix. There are a lot of considerations there, and I've split it off into https://github.com/oconnor663/bao/issues/22.
