### ISSUE TITLE
Publish latest?

### ISSUE THREAD

**Issue by cryptoquick** [oconnor663/bao#37]
I get conflicts if I try to use both the Hash trait from the blake3 crate and the bao crate, and the currently published bao crate includes an older copy of blake3. I don't suppose you could pop a new one up? It's preventing me from publishing.

BTW, your documentation is really good, and the bao binary serves as an excellent example and is really well-written. Thanks!

**Comment by oconnor663** [comment]
Thank you for the reminder! I just released version 0.12.0.
